name: Build and Push Docker Images

on:
#  workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME_API: placeholder/[placeholder-api
  IMAGE_NAME_CLIENT: placeholder/placeholder-client
  IMAGE_NAME_ADMIN: placeholder/placeholder-admin

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push API Image
        run: |
          docker build -f docker/api.Dockerfile -t $REGISTRY/${IMAGE_NAME_API}:latest .
          docker push $REGISTRY/${IMAGE_NAME_API}:latest

      - name: Build and Push Client Image
        run: |
          docker build -f docker/angular.Dockerfile \
            --build-arg APP_DIR=apps/client-frontend \
            -t $REGISTRY/${IMAGE_NAME_CLIENT}:latest .
          docker push $REGISTRY/${IMAGE_NAME_CLIENT}:latest

      - name: Build and Push Admin Image
        run: |
          docker build -f docker/angular.Dockerfile \
            --build-arg APP_DIR=apps/admin-frontend \
            -t $REGISTRY/${IMAGE_NAME_ADMIN}:latest .
          docker push $REGISTRY/${IMAGE_NAME_ADMIN}:latest
